"""Read-only tests of the actual Bash preflight, not a reimplementation.

Fixtures reproduce the supplied Ubuntu 24.04 / ufw 0.36.2-6 incident.
No ufw command, kernel ruleset, system path or installation is modified.
"""
import hashlib
import os
from pathlib import Path
import re
import subprocess
import tempfile
import unittest

from common import ROOT, SCRIPT

FIXTURES = ROOT / 'tests/fixtures/ufw/ubuntu-24.04-0.36.2-6'
V4 = (FIXTURES / 'user.rules').read_text()
V6 = (FIXTURES / 'user6.rules').read_text()


class SavedUfwPreflightTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix='vk-ufw-preflight-')
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.rules = self.root / 'rules with spaces'
        self.rules.mkdir()
        (self.rules / 'user.rules').write_text(V4)
        (self.rules / 'user6.rules').write_text(V6)

    def run_check(self, v4=None, v6=None, *, integration=False, env=None):
        for name, text in (('user.rules', v4), ('user6.rules', v6)):
            if text is not None:
                (self.rules / name).write_text(text)
        if integration:
            start = SCRIPT.index('    if ! vk_check_saved_ufw_rules; then\n')
            end = SCRIPT.index('    for p in /etc/docker/daemon.json ', start)
            gate = SCRIPT[start:end]
            # The sole alteration redirects the helper from /etc to fixture files.
            gate = gate.replace('vk_check_saved_ufw_rules;', 'vk_check_saved_ufw_rules "$2";')
            command = gate + 'printf "REACHED_NEXT_PREFLIGHT\\n"\n'
        else:
            command = 'vk_check_saved_ufw_rules "$2"\n'
        return subprocess.run(
            ['bash', '-c', 'set -Eeuo pipefail; source "$1"\n' + command,
             '_', str(ROOT / 'install.sh'), str(self.rules)],
            text=True, capture_output=True, timeout=5, env=env)

    def accepted(self, *args, **kwargs):
        result = self.run_check(*args, **kwargs)
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        return result

    def refused(self, *args, **kwargs):
        result = self.run_check(*args, **kwargs)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertNotIn('REACHED_NEXT_PREFLIGHT', result.stdout)
        return result

    def with_rule(self, rule, *, ipv6=False):
        text = (V6 if ipv6 else V4).replace('COMMIT\n', rule + '\nCOMMIT\n')
        return {'v6' if ipv6 else 'v4': text}

    def test_incident_is_reproduced_by_previous_201_predicate(self):
        previous = "_contains() { grep \"$@\" >/dev/null; }; "
        previous += 'if grep -E "^-A ufw-user-" "$1" | _contains .; then exit 42; fi'
        result = subprocess.run(['bash', '-o', 'pipefail', '-c', previous, '_',
                                 str(self.rules / 'user.rules')], capture_output=True, timeout=5)
        self.assertEqual(result.returncode, 42)

    def test_exact_operator_files_accepted(self): self.accepted()
    def test_actual_install_gate_accepts_exact_operator_files(self):
        self.assertIn('REACHED_NEXT_PREFLIGHT', self.accepted(integration=True).stdout)
    def test_actual_install_gate_stops_on_saved_user_rule(self):
        result = self.refused(**self.with_rule('-A ufw-user-input -p tcp --dport 22 -j ACCEPT'), integration=True)
        self.assertIn('STOP:', result.stderr)
    def test_install_gate_precedes_credentials_and_package_changes(self):
        main = SCRIPT[SCRIPT.index('vkarmani_main() {'):]
        self.assertLess(main.index('if ! vk_check_saved_ufw_rules;'), main.index('\nvk_collect_inputs\n'))
        self.assertNotIn("grep -E '^-A ufw-user-'", SCRIPT)
    def test_absent_ufw_files_accepted(self):
        for file in self.rules.iterdir(): file.unlink()
        self.accepted()
    def test_absent_ipv6_file_accepted(self):
        (self.rules / 'user6.rules').unlink()
        self.accepted()
    def test_absent_ipv4_file_does_not_skip_ipv6_rules(self):
        (self.rules / 'user.rules').unlink()
        self.refused(**self.with_rule('-A ufw6-user-input -p tcp --dport 22 -j ACCEPT', ipv6=True))
    def test_minimal_ipv4_skeleton_accepted(self): self.accepted(v4=V6.replace('ufw6-', 'ufw-'))
    def test_ipv6_complete_stock_helpers_accepted(self): self.accepted(v6=V4.replace('ufw-', 'ufw6-'))
    def test_comments_blank_lines_and_section_markers_accepted(self):
        self.accepted(v4='# Generated by ufw\n\n' + V4.replace('COMMIT', '### END RATE LIMITING ###\nCOMMIT') + '# end\n')
    def test_indentation_and_nonzero_counters_accepted(self):
        self.accepted(v4='\n'.join(' \t' + x + '\t ' for x in V4.replace('[0:0]', '[7:4096]').splitlines()) + '\n')
    def test_missing_final_newline_accepted(self): self.accepted(v4=V4.rstrip('\n'), v6=V6.rstrip('\n'))
    def test_saved_ipv4_inbound_rule_refused(self): self.refused(**self.with_rule('-A ufw-user-input -p tcp --dport 22 -j ACCEPT'))
    def test_saved_ipv4_outbound_rule_refused(self): self.refused(**self.with_rule('-A ufw-user-output -p tcp --dport 25 -j DROP'))
    def test_saved_ipv4_route_rule_refused(self): self.refused(**self.with_rule('-A ufw-user-forward -j ACCEPT'))
    def test_saved_ipv6_inbound_rule_refused(self): self.refused(**self.with_rule('-A ufw6-user-input -p tcp --dport 22 -j ACCEPT', ipv6=True))
    def test_saved_ipv6_outbound_rule_refused(self): self.refused(**self.with_rule('-A ufw6-user-output -j DROP', ipv6=True))
    def test_saved_ipv6_route_rule_refused(self): self.refused(**self.with_rule('-A ufw6-user-forward -j ACCEPT', ipv6=True))
    def test_real_ufw_limit_rule_is_not_ignored(self): self.refused(**self.with_rule('-A ufw-user-input -p tcp --dport 22 -j ufw-user-limit'))
    def test_changed_helper_action_refused(self): self.refused(v4=V4.replace('-j REJECT', '-j ACCEPT'))
    def test_added_condition_to_helper_refused(self): self.refused(v4=V4.replace('-j REJECT', '-p tcp --dport 22 -j REJECT'))
    def test_changed_helper_logging_refused(self): self.refused(v4=V4.replace('--limit 3/minute', '--limit 60/minute'))
    def test_limit_name_suffix_is_not_a_bypass(self): self.refused(**self.with_rule('-A ufw-user-limit-extra -j ACCEPT'))
    def test_custom_chain_refused(self): self.refused(v4=V4.replace('### RULES ###', ':custom - [0:0]\n### RULES ###'))
    def test_manual_builtin_input_rule_refused(self): self.refused(**self.with_rule('-A INPUT -j ACCEPT'))
    def test_manual_iptables_insert_refused(self): self.refused(**self.with_rule('-I ufw-user-input -j ACCEPT'))
    def test_builtin_policy_refused(self): self.refused(v4=V4.replace('### RULES ###', ':INPUT ACCEPT [0:0]\n### RULES ###'))
    def test_extra_table_refused(self): self.refused(v4=V4 + '*nat\n:PREROUTING ACCEPT [0:0]\nCOMMIT\n')
    def test_duplicate_table_refused(self): self.refused(v4=V4 + V4)
    def test_tuple_metadata_without_rule_refused(self):
        result = self.refused(v4=V4.replace('### RULES ###', '### RULES ###\n### tuple ### allow tcp 22 0.0.0.0/0 any 0.0.0.0/0 in'))
        self.assertIn('USER_RULE_METADATA', result.stderr)
    def test_whitespace_before_tuple_metadata_refused(self): self.refused(**self.with_rule(' \t### tuple ### allow tcp 22'))
    def test_empty_file_refused(self): self.refused(v4='')
    def test_missing_commit_refused(self): self.refused(v4=V4.replace('COMMIT\n', ''))
    def test_missing_filter_header_refused(self): self.refused(v4=V4.replace('*filter\n', ''))
    def test_missing_required_chain_refused(self): self.refused(v6=V6.replace(':ufw6-user-forward - [0:0]\n', ''))
    def test_missing_helper_rule_refused(self): self.refused(v4=V4.replace('-A ufw-user-limit -j REJECT\n', ''))
    def test_duplicate_helper_rule_refused(self): self.refused(**self.with_rule('-A ufw-user-limit -j REJECT'))
    def test_duplicate_chain_refused(self): self.refused(v4=V4.replace('### RULES ###', ':ufw-user-input - [0:0]\n### RULES ###'))
    def test_wrong_address_family_refused(self): self.refused(v6=V4)
    def test_regular_file_symlink_refused(self):
        target = self.rules / 'user.rules'
        target.rename(self.rules / 'original.rules')
        target.symlink_to(self.rules / 'original.rules')
        self.refused()
    def test_dangling_symlink_refused(self):
        target = self.rules / 'user6.rules'; target.unlink(); target.symlink_to(self.rules / 'not-present')
        self.refused()
    def test_directory_refused(self):
        target = self.rules / 'user.rules'; target.unlink(); target.mkdir()
        self.refused()
    def test_fifo_refused_without_hanging(self):
        target = self.rules / 'user.rules'; target.unlink(); os.mkfifo(target)
        self.refused()
    def test_success_and_failure_never_modify_input_files(self):
        def snapshot():
            return {p.name: (hashlib.sha256(p.read_bytes()).hexdigest(), p.stat().st_mode,
                             p.stat().st_mtime_ns, p.stat().st_ino) for p in self.rules.iterdir()}
        before = snapshot(); self.accepted(); self.assertEqual(before, snapshot())
        target = self.rules / 'user.rules'; target.write_text(V4.replace('-j REJECT', '-j ACCEPT'))
        before = snapshot(); self.refused(); self.assertEqual(before, snapshot())
    def test_rule_contents_are_not_dumped_on_failure(self):
        result = self.refused(**self.with_rule('-A ufw-user-input -m comment --comment "DO_NOT_ECHO_RULE_CONTENTS" -j ACCEPT'))
        self.assertNotIn('DO_NOT_ECHO_RULE_CONTENTS', result.stdout + result.stderr)
    def test_awk_failure_is_not_treated_as_empty_ruleset(self):
        commands = self.root / 'bin'; commands.mkdir()
        fake = commands / 'awk'; fake.write_text('#!/bin/sh\nexit 23\n'); fake.chmod(0o700)
        env = dict(os.environ, PATH=str(commands) + os.pathsep + os.environ.get('PATH', '/usr/bin:/bin'))
        result = self.refused(integration=True, env=env)
        self.assertIn('STOP:', result.stderr)
    def test_preflight_does_not_call_firewall_or_service_commands(self):
        commands = self.root / 'bin'; commands.mkdir()
        marker = self.root / 'forbidden-call'
        for name in ('ufw', 'nft', 'iptables', 'iptables-restore', 'ip6tables', 'systemctl', 'service'):
            file = commands / name
            file.write_text('#!/bin/sh\nprintf CALLED > "$VK_FORBIDDEN_MARKER"\nexit 99\n')
            file.chmod(0o700)
        env = dict(os.environ, PATH=str(commands) + os.pathsep + os.environ.get('PATH', '/usr/bin:/bin'),
                   VK_FORBIDDEN_MARKER=str(marker))
        self.accepted(env=env)
        self.assertFalse(marker.exists())


if __name__ == '__main__':
    unittest.main()
