"""Node 12 API compatibility without skipping the JS comparison or changing TLS."""
import json
import re
import shutil
import subprocess
import unittest

from common import certificate_bundle, module
from node_hkdf_oracle import NODE_HKDF_ORACLE, NODE_SNI_PROGRAM

# RFC 5869 Appendix A.1, A.2, A.3. Fixed expected outputs, NOT generated by us.
# https://www.rfc-editor.org/rfc/rfc5869.html#appendix-A
VECTORS = [
    dict(ikm='0b' * 22, salt='000102030405060708090a0b0c', info='f0f1f2f3f4f5f6f7f8f9', length=42,
         expected='3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865'),
    dict(ikm=bytes(range(0x00, 0x50)).hex(), salt=bytes(range(0x60, 0xb0)).hex(),
         info=bytes(range(0xb0, 0x100)).hex(), length=82,
         expected='b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c'
                  '59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71'
                  'cc30c58179ec3e87c14c01d5c1f3434f1d87'),
    dict(ikm='0b' * 22, salt='', info='', length=42,
         expected='8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d9d201395faa4b61a96c8'),
]
DISABLE_NATIVE = "require('crypto').hkdfSync = undefined;\n"


@unittest.skipUnless(shutil.which('node'), 'Node.js absent: independent JS oracle needs Node')
class HkdfCompatibilityTests(unittest.TestCase):
    def node(self, program, data=None, ok=True):
        result = subprocess.run(['node', '-e', program], input=json.dumps(data), text=True,
                                capture_output=True, timeout=5)
        if ok:
            self.assertEqual(result.returncode, 0, result.stderr)
        return result

    def check_vectors(self, prefix):
        program = prefix + NODE_HKDF_ORACLE + r"""
const vectors = JSON.parse(require('fs').readFileSync(0, 'utf8'));
const hex = value => Buffer.from(value, 'hex');
process.stdout.write(JSON.stringify(vectors.map(v =>
    hkdfSha256(hex(v.ikm), hex(v.salt), hex(v.info), v.length).toString('hex'))));
"""
        self.assertEqual(json.loads(self.node(program, VECTORS).stdout), [v['expected'] for v in VECTORS])

    def test_rfc5869_fixed_vectors_runtime_selected_backend(self):
        self.check_vectors('')

    def test_rfc5869_fixed_vectors_without_native_api(self):
        self.check_vectors(DISABLE_NATIVE)

    def test_node12_api_path_matches_embedded_sni_and_cryptography(self):
        bundle, _ = certificate_bundle()
        public = {k: bundle[k] for k in ('caCertPem', 'jwtPublicKey')}
        result = self.node(DISABLE_NATIVE + NODE_SNI_PROGRAM, public).stdout
        helper = module('VK_PAYLOAD_VK_WRITE_TLS_CHECK')
        self.assertEqual(result, helper.derive_sni(public['caCertPem'], public['jwtPublicKey']))
        from cryptography.hazmat.primitives import hashes
        from cryptography.hazmat.primitives.kdf.hkdf import HKDF
        canonical = lambda v: re.sub(r'[^A-Za-z0-9+/=]', '', re.sub(r'-----[^-]+-----', '', v)).encode()
        output = HKDF(algorithm=hashes.SHA256(), length=22, salt=b'', info=b'rw-v1').derive(
            canonical(public['jwtPublicKey']) + canonical(public['caCertPem']))
        expected = output[:16].hex() + '.' + output[16:21].hex() + '.' + (
            'com', 'net', 'org', 'io', 'dev', 'app')[output[21] % 6]
        self.assertEqual(result, expected)
        self.assertEqual(result, self.node(NODE_SNI_PROGRAM, public).stdout)

    def test_missing_api_path_canonicalizes_pem_whitespace(self):
        bundle, _ = certificate_bundle()
        public = {k: bundle[k] for k in ('caCertPem', 'jwtPublicKey')}
        expected = self.node(DISABLE_NATIVE + NODE_SNI_PROGRAM, public).stdout
        changed = {k: '\r\n  ' + v.replace('\n', '\r\n \t') + '\n' for k, v in public.items()}
        self.assertEqual(expected, self.node(DISABLE_NATIVE + NODE_SNI_PROGRAM, changed).stdout)

    def test_existing_native_api_is_used_not_silently_replaced(self):
        program = "require('crypto').hkdfSync = () => { throw new Error('NATIVE_PATH_SENTINEL'); };\n"
        program += NODE_HKDF_ORACLE + "hkdfSha256(Buffer.from('key'), Buffer.alloc(0), Buffer.alloc(0), 22);"
        result = self.node(program, ok=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('NATIVE_PATH_SENTINEL', result.stderr)

    def test_portable_output_length_bounds(self):
        program = DISABLE_NATIVE + NODE_HKDF_ORACLE + r"""
const key = Buffer.from('fixture');
const empty = Buffer.alloc(0);
const lengths = [0, 1, 22, 32, 33, 82, 8160];
const output = lengths.map(n => hkdfSha256(key, empty, empty, n).length);
const rejected = [-1, 8161, 1.5].map(n => {
    try { hkdfSha256(key, empty, empty, n); return false; }
    catch (e) { return e instanceof RangeError; }
});
process.stdout.write(JSON.stringify({output, rejected}));
"""
        self.assertEqual(json.loads(self.node(program).stdout),
                         dict(output=[0, 1, 22, 32, 33, 82, 8160], rejected=[True, True, True]))


if __name__ == '__main__':
    unittest.main()
